### ISSUE TITLE
<number> <space> <from-unit-name> doesn't work here

### ISSUE THREAD

**Issue by s-oram** [DrorHarari/keypirinha-cvt#1] opened 2018-11-06 03:34 UTC
Hi, I just installed CVT via PackageControl in Keypirinha version 2.21 for x64. 

Typing the command sequence `<number> <space> <from-unit-name>` doesn't work here. 

After typing a number, it's not possible to add a space. Dropping the space and typing `400kg`  also has no results (perhaps expectedly so). 

Here's an animated gif showing the lack of results. 
![400kg](https://user-images.githubusercontent.com/1150429/48041332-c1764180-e1d0-11e8-9b49-838affe65857.gif)

CVT is installed. The plugin is shown as loaded in the KP console and typing CVT does show CVT provided catalogue items.

**Comment by DrorHarari** [comment] 2018-11-06 06:28
Hi Shanon. For Cvt to work, there must be a space after the number - in order to save resources, it only starts looking for the units once the number entry is complete.

Now you say you can't type a space after the number? You mean you type the digits and then typing space does not move the cursor? I don't have this here, even without Cvt, I can type "123 456" - it won't give Cvt suggestions but it would let me place the space between 123 and 456.

Is it always like that on your KP? Could there be another KP settings or plugin that steals the space?

@s-oram

**Comment by s-oram** [comment] 2018-11-06 08:03
Yes, I'm using the `space_as_tab = true` setting.

**Comment by DrorHarari** [comment] 2018-11-06 08:09
OK - managed to recreate this. I'll look into finding a solution for that. I wonder if a plugin can detect this mode.

**Comment by s-oram** [comment] 2018-11-06 08:20
If it helps, I think it would be ok to type `convert <space/tab> <number> <space/tab> <from-unit-name>`.

**Comment by DrorHarari** [comment] 2018-11-06 10:10
The problem is that tab is not captured in the input string. The solution is to improve the regex to cover the case of no-space so, for example, 12kg will be valid. I'll make the change when I have some time.

**Comment by DrorHarari** [comment] 2018-11-07 03:28
Fixed in a new release here (v1.0.1) - will take a day to get updated in PackageControl. One can now type 12kg. In order to add target unit, one can use any non alphanumeric character except '/'. For example 12g,kg

**Closed as completed by DrorHarari** 2018-11-07 03:28 UTC

**Comment by polyvertex** [comment] 2018-11-09 17:18
@DrorHarari FYI, I didn't have a look at the source code of your plugin so not sure this is really what you need but in case you do, be aware it is possible for a plugin to read Keypirinha's config using the [keypirinha.settings](http://keypirinha.com/api/module.html#keypirinha.settings) function.

**Comment by s-oram** [comment] 2018-11-10 09:49
Thanks DrorHarari, that works here now!
